
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 24 17:33:08 CST 2011
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERICO = 20;
  public static final int SIG_SUMA = 14;
  public static final int DOSPUNTOS = 5;
  public static final int IGUAL = 9;
  public static final int SIG_MULTIPLICACION = 15;
  public static final int ETIQUETA = 22;
  public static final int MENORQ = 17;
  public static final int COMA = 6;
  public static final int MAYORQ = 16;
  public static final int EOF = 0;
  public static final int COMILLA = 18;
  public static final int ALFANUMERICO = 19;
  public static final int PARENTESIS_C = 3;
  public static final int error = 1;
  public static final int DIAGONAL = 7;
  public static final int PARENTESIS_A = 2;
  public static final int LLAVE_C = 11;
  public static final int ATRIBUTO = 23;
  public static final int PUNTOCOMA = 4;
  public static final int LLAVE_A = 10;
  public static final int SIG_RESTA = 8;
  public static final int CORCHETE_C = 13;
  public static final int ALFABETICO = 21;
  public static final int CORCHETE_A = 12;
}

